version: '3.8'

services:
  
  user-service:
    build:
      context: .
      dockerfile: user-service/dockerfile
    image: user-service
    ports:
      - 80:8080
    depends_on:
      - notification-service


  notification-service:
    build:
      context: .
      dockerfile: notification-service/dockerfile
    image: notification-service